version: "3"
services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile"
    command: python main.py
    volumes:
      - .:/app
      # virtualenv の仮想環境が配置される場所を設定
      - python-packages:/root/.local/share
      - ./src:/src
volumes:
  python-packages: