version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv run pylint main.py