version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run:
          name: install Pipenv
          command: sudo pip install pipenv
      - run:
          name: Run pipenv install
          command: pipenv install
      - run:
          name: Run pylint
          command: pipenv run pylint main.py
